CREATE OR ALTER PROCEDURE ELIMINAR_PRESTAMO
    @IDLECTOR INT,
    @IDLIBRO INT


    -- EXEC ELIMINAR_PRESTAMO 
    -- @IDLECTOR = 3, 
    -- @IDLIBRO = 5;

AS
BEGIN
    DELETE FROM PRESTAMO
    WHERE IDLECTOR = @IDLECTOR AND IDLIBRO = @IDLIBRO;
END;
