CREATE OR ALTER PROCEDURE INSERTAR_PRESTAMO
    @IDLECTOR INT,
    @IDLIBRO INT,
    @FECHAPRESTAMO DATE,
    @DEVUELTO BIT


    -- EXEC INSERTAR_PRESTAMO 
    -- @IDLECTOR = 1, 
    -- @IDLIBRO = 1, 
    -- @FECHAPRESTAMO = '2024-11-20', 
    -- @DEVUELTO = 0;

AS
BEGIN
    INSERT INTO PRESTAMO (IDLECTOR, IDLIBRO, FECHAPRESTAMO, DEVUELTO)
    VALUES (@IDLECTOR, @IDLIBRO, @FECHAPRESTAMO, @DEVUELTO);
END;
