CREATE OR ALTER PROCEDURE INSERTAR_ESTUDIANTE
    @CI VARCHAR(255),
    @NOMBRE VARCHAR(255),
    @DIRECCION VARCHAR(255),
    @CARRERA VARCHAR(255),
    @EDAD INT

    -- EXEC INSERTAR_ESTUDIANTE 
    -- @CI = '001', 
    -- @NOMBRE = 'ESTUDIANTE A', 
    -- @DIRECCION = 'CALLE A', 
    -- @CARRERA = 'INGENIERÍA', 
    -- @EDAD = 20;

AS
BEGIN
    INSERT INTO ESTUDIANTE (CI, NOMBRE, DIRECCION, CARRERA, EDAD)
    VALUES (@CI, @NOMBRE, @DIRECCION, @CARRERA, @EDAD);
END;
