CREATE OR ALTER PROCEDURE MODIFICAR_ESTUDIANTE
    @IDLECTOR INT,
    @CI VARCHAR(255),
    @NOMBRE VARCHAR(255),
    @DIRECCION VARCHAR(255),
    @CARRERA VARCHAR(255),
    @EDAD INT

    -- EXEC MODIFICAR_ESTUDIANTE 
    -- @IDLECTOR = 1, @CI = '002', 
    -- @NOMBRE = 'ESTUDIANTE B', 
    -- @DIRECCION = 'CALLE B CALLE B', 
    -- @CARRERA = 'MEDICINA', 
    -- @EDAD = 22;

AS
BEGIN
    UPDATE ESTUDIANTE
    SET CI = @CI,
        NOMBRE = @NOMBRE,
        DIRECCION = @DIRECCION,
        CARRERA = @CARRERA,
        EDAD = @EDAD
    WHERE IDLECTOR = @IDLECTOR;
END;
