-- CREA LAS TABLAS
--  Por temas de pruebas se comentan relaciones entre tablas.



CREATE TABLE LIBRO (
    IDLIBRO INT PRIMARY KEY IDENTITY(1,1),
    TITULO VARCHAR(255) NOT NULL,
    EDITORIAL VARCHAR(255)  NULL,
    AREA VARCHAR(255)  NULL

);

CREATE TABLE AUTOR (
    IDAUTOR INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(255) NOT NULL,
    NACIONALIDAD VARCHAR(255) NULL
);

CREATE TABLE LIB_AUTOR (
    IDAUTOR INT NOT NULL,
    IDLIBRO INT NOT NULL
    FOREIGN KEY (IDAUTOR) REFERENCES AUTOR(IDAUTOR) ON DELETE CASCADE,
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO) ON DELETE CASCADE
);




----------------------------
CREATE TABLE ESTUDIANTE (
    IDLECTOR INT PRIMARY KEY IDENTITY(1,1),
    CI VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    CARRERA VARCHAR(255) NOT NULL,
    EDAD INT NULL
);


CREATE TABLE PRESTAMO (
    IDPRESTAMO INT PRIMARY KEY IDENTITY(1,1),
    IDLECTOR INT NOT NULL,
    IDLIBRO INT NOT NULL,
    FECHAPRESTAMO DATE NOT NULL,
    FECHAENTREGA DATE NULL,
    DEVUELTO BIT NOT NULL -- 1 para "Sí", 0 para "No"

    FOREIGN KEY (IDLECTOR) REFERENCES ESTUDIANTE(IDLECTOR) ON DELETE CASCADE,
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO) ON DELETE CASCADE

);