CREATE OR ALTER VIEW VISTA_PRESTAMOS_ANTIGUOS AS

-- SELECT * FROM VISTA_PRESTAMOS_ANTIGUOS;

SELECT 
    E.NOMBRE AS NOMBRE_ESTUDIANTE,
    L.TITULO AS TITULO_LIBRO,
    A.NOMBRE AS NOMBRE_AUTOR,
    P.FECHAPRESTAMO AS FECHA_PRESTAMO,
    P.FECHAENTREGA AS FECHA_DEVOLUCION, -- Asumiendo 15 días de préstamo
    CASE 
        WHEN P.DEVUELTO = 1 THEN 'Sí'
        ELSE 'No'
    END AS DEVUELTO
FROM 
PRESTAMO P
INNER JOIN ESTUDIANTE E ON P.IDLECTOR = E.IDLECTOR
INNER JOIN LIBRO L ON P.IDLIBRO = L.IDLIBRO
INNER JOIN LIB_AUTOR LA ON L.IDLIBRO = LA.IDLIBRO
INNER JOIN AUTOR A ON LA.IDAUTOR = A.IDAUTOR
WHERE 
    P.FECHAPRESTAMO = (
        SELECT MIN(P1.FECHAPRESTAMO)
        FROM PRESTAMO P1
        WHERE P1.IDLECTOR = P.IDLECTOR
    );
